services:
  - type: web
    name: falsepeoplesearch
    env: python
    buildCommand: |
      # Install Chrome
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
      
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: CHROME_HEADLESS
        value: "true"
      - key: CHROME_TIMEOUT
        value: "30"
      - key: MIN_DELAY
        value: "5.0"
      - key: MAX_DELAY
        value: "10.0"
      - key: BATCH_SIZE
        value: "3"
    healthCheckPath: /
    autoDeploy: true